In [1]:
import pandas as pd

In [2]:
data= pd.read_csv("hiring.csv")

In [3]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
import math
mean = math.floor(data['test_score(out of 10)'].mean())

In [5]:
data.experience.fillna("zero", inplace= True)
data['test_score(out of 10)'].fillna(mean, inplace= True)

In [6]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [8]:
from word2number import w2n

In [9]:
data.experience= data.experience.apply(w2n.word_to_num)

In [10]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
Train_data= data.to_numpy()

In [12]:
Train_data[:,-1]

array([50000., 45000., 60000., 65000., 70000., 62000., 72000., 80000.])

In [13]:
X_train= Train_data[:, :-1]
Y_train= Train_data[:,-1]

In [14]:
from sklearn import linear_model

In [15]:
reg = linear_model.LinearRegression()
reg.fit(X_train, Y_train)

LinearRegression()

In [16]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [17]:
reg.predict([[12,10,10]])

array([93747.79628651])